<a href="https://colab.research.google.com/github/legna7816/ml-projects/blob/main/basic/scikit_learn_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris, make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error, r2_score

In [ ]:
iris = load_iris()
X = iris.data
y = iris.target

df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y
print(df.head())
print(df['species'].value_counts())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  
species
0    50
1    50
2    50
Name: count, dtype: int64


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)
print(X_train.shape, X_test.shape)

(105, 4) (45, 4)


In [ ]:
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(y_pred[:10])
print(y_test[:10])

[1 0 2 1 1 0 1 2 1 1]
[1 0 2 1 1 0 1 2 1 1]


In [ ]:
print('정확도: ', accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

정확도:  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [ ]:
tree_model = DecisionTreeClassifier(max_depth=3)
tree_model.fit(X_train, y_train)
tree_pred = tree_model.predict(X_test)

print('decisionTree 정확도: ', accuracy_score(y_test, tree_pred))

decisionTree 정확도:  1.0


In [ ]:
X_reg, y_reg = make_regression(n_samples=200, n_features=1, noise=15, random_state=42)
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(
    X_reg, y_reg, test_size=0.3, random_state=42
)

reg_model = LinearRegression()
reg_model.fit(X_reg_train, y_reg_train)
y_reg_pred = reg_model.predict(X_reg_test)

print('MSE: ', mean_squared_error(y_reg_test, y_reg_pred))
print('R2: ', r2_score(y_reg_test, y_reg_pred))

MSE:  261.5702418137988
R2:  0.9702903588877088


In [ ]:
from sklearn.model_selection import cross_val_score

log_scores = cross_val_score(LogisticRegression(max_iter=200), X, y, cv=5)
tree_scores = cross_val_score(DecisionTreeClassifier(random_state=42), X, y, cv=5)

print('Logistic 평균:', log_scores.mean(), log_scores)
print('Tree 평균:', tree_scores.mean(), tree_scores)

Logistic 평균: 0.9733333333333334 [0.96666667 1.         0.93333333 0.96666667 1.        ]
Tree 평균: 0.9533333333333334 [0.96666667 0.96666667 0.9        0.93333333 1.        ]
